version: "3.8"

services:
  simple-map:
    image: "simple-map"
    container_name: "simple-map"
    build: "./"
    working_dir: "/usr/share/nginx/html/"
    volumes:
      - "./src/:/usr/share/nginx/html/"
    ports:
      - "5000:80"
    restart:
      "on-failure"
